# Generated by Django 5.2.6 on 2025-09-12 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('tecnologia', models.CharField(max_length=10)),
                ('rut_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('id_vivienda', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_cliente', models.CharField(max_length=255)),
                ('estado_cliente', models.CharField(choices=[('autoriza', 'Autoriza a ingresar'), ('sin_moradores', 'Sin Moradores'), ('rechaza', 'Rechaza'), ('contingencia', 'Contingencia externa'), ('masivo', 'Incidencia Masivo ClaroVTR'), ('reagendo', 'Reagendó')], max_length=20)),
                ('ont_modem_ok', models.BooleanField(blank=True, null=True)),
                ('bloque_agendamiento', models.JSONField(blank=True, null=True)),
                ('bloque_llegada', models.JSONField(blank=True, null=True)),
                ('bloque_proceso', models.JSONField(blank=True, null=True)),
                ('bloque_config', models.JSONField(blank=True, null=True)),
                ('bloque_cierre', models.JSONField(blank=True, null=True)),
                ('percepcion', models.JSONField(blank=True, null=True)),
                ('descripcion_problema', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='asignaciones.direccionasignada')),
            ],
            options={
                'db_table': 'auditorias',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('internet', 'Internet'), ('tv', 'TV'), ('fono', 'Fono'), ('otro', 'Otro')], max_length=10)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='auditoria.auditoria')),
            ],
            options={
                'db_table': 'auditoria_servicios',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('extra', models.TextField(blank=True, null=True)),
                ('auditoria_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='auditoria.auditoriaservicio')),
            ],
            options={
                'db_table': 'auditoria_categorias',
            },
        ),
        migrations.CreateModel(
            name='EvidenciaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('firma', 'Firma'), ('comprobante', 'Comprobante'), ('otro', 'Otro')], default='foto', max_length=20)),
                ('archivo', models.ImageField(upload_to='auditorias/%Y/%m/%d/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='asignaciones.direccionasignada')),
                ('auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='auditoria.auditoria')),
            ],
            options={
                'db_table': 'evidencias_servicio',
            },
        ),
    ]
