# Generated by Django 5.2.6 on 2025-11-04 19:43

import auditoria.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0008_alter_direccionasignada_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_status', models.CharField(blank=True, choices=[('AUTORIZA', 'Autoriza a ingresar'), ('SIN_MORADORES', 'Sin Moradores'), ('RECHAZA', 'Rechaza'), ('CONTINGENCIA', 'Contingencia externa'), ('MASIVO', 'Incidencia Masivo ClaroVTR'), ('REAGENDA', 'Reagendó')], max_length=20)),
                ('reschedule_date', models.DateField(blank=True, db_column='reagendado_fecha', null=True)),
                ('reschedule_slot', models.CharField(blank=True, db_column='reagendado_bloque', help_text='Usar 10-13 o 14-18', max_length=10)),
                ('ont_modem_ok', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], default=3)),
                ('service_issues', models.JSONField(blank=True, db_column='servicios', default=list)),
                ('internet_categoria', models.CharField(blank=True, choices=[('lento', 'Navegaba muy lento'), ('wifi_alcance', 'Señal del Wifi con bajo alcance'), ('cortes', 'Cortes/Días sin servicio'), ('intermitencia', 'Intermitencia de la Señal de Internet'), ('otro', 'Otro')], max_length=32)),
                ('internet_otro', models.CharField(blank=True, max_length=200)),
                ('tv_categoria', models.CharField(blank=True, choices=[('sin_senal', 'Me quedaba sin señal de TV'), ('pixelado', 'Se pixelaba la imagen de TV'), ('intermitencia', 'Intermitencia de la Señal'), ('desfase', 'Presenta desfase con la señal en vivo'), ('streaming', 'Problemas con Plataforma de Streaming'), ('zapping', 'Problemas con zapping (lentitud)'), ('equipos', 'Problemas con Equipos (Dbox, Control, IPTV)'), ('otro', 'Otro')], max_length=32)),
                ('tv_otro', models.CharField(blank=True, max_length=200)),
                ('otro_descripcion', models.TextField(blank=True)),
                ('photo1', models.ImageField(blank=True, db_column='foto1', null=True, upload_to=auditoria.models._upload_auditoria)),
                ('photo2', models.ImageField(blank=True, db_column='foto2', null=True, upload_to=auditoria.models._upload_auditoria)),
                ('photo3', models.ImageField(blank=True, db_column='foto3', null=True, upload_to=auditoria.models._upload_auditoria)),
                ('desc_hfc', models.TextField(blank=True)),
                ('schedule_informed_datetime', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='agend_inf_fecha_hora', default=3)),
                ('schedule_informed_adult_required', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='agend_aviso_adulto', default=3)),
                ('schedule_informed_services', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='agend_comunicacion_servicios', default=3)),
                ('agend_comentarios', models.TextField(blank=True)),
                ('arrival_within_slot', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='llego_en_horario', default=3)),
                ('identification_shown', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='se_identifico', default=3)),
                ('explained_before_start', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='explico_antes', default=3)),
                ('llegada_comentarios', models.TextField(blank=True)),
                ('asked_equipment_location', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='consulto_ubicacion', default=3)),
                ('tidy_and_safe_install', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='ordenado_seguro', default=3)),
                ('tidy_cabling', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='cableado_prolijo', default=3)),
                ('verified_signal_levels', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='verifico_niveles', default=3)),
                ('proceso_comentarios', models.TextField(blank=True)),
                ('configured_router', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='config_router', default=3)),
                ('tested_device', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='probo_dispositivo', default=3)),
                ('tv_functioning', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='tv_ok', default=3)),
                ('left_instructions', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='dejo_instrucciones', default=3)),
                ('config_comentarios', models.TextField(blank=True)),
                ('reviewed_with_client', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='revision_con_cliente', default=3)),
                ('got_consent_signature', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='pidio_conformidad', default=3)),
                ('left_contact_info', models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='dejo_contacto', default=3)),
                ('cierre_comentarios', models.TextField(blank=True)),
                ('percepcion', models.TextField(blank=True)),
                ('nps_proceso', models.PositiveSmallIntegerField(blank=True, db_column='nps_proceso', null=True)),
                ('nps_tecnico', models.PositiveSmallIntegerField(blank=True, db_column='nps_tecnico', null=True)),
                ('nps_claro_vtr', models.PositiveSmallIntegerField(blank=True, db_column='nps_claro_vtr', null=True)),
                ('solucion_gestion', models.CharField(blank=True, choices=[('terreno', 'Se solucionó en terreno'), ('orden', 'Se realizó una gestión con Orden')], db_column='solucion_gestion', max_length=16)),
                ('orden_tipo', models.CharField(blank=True, choices=[('tecnica', 'Técnica'), ('comercial', 'Comercial')], db_column='orden_tipo', max_length=16)),
                ('info_tipo', models.CharField(blank=True, choices=[('mala_practica', 'Mala Práctica'), ('problema_general', 'Problema General')], db_column='info_tipo', max_length=20)),
                ('detalle_mala_practica_empresa', models.CharField(blank=True, db_column='detalle_mala_practica_empresa', max_length=200)),
                ('detalle_mala_practica_instalador', models.CharField(blank=True, db_column='detalle_mala_practica_instalador', max_length=200)),
                ('descripcion_problema', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='asignaciones.direccionasignada')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de visita',
                'verbose_name_plural': 'Auditorías de visitas',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
