# Generated by Django 5.2.6 on 2025-09-03 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True)),
                ('nombre_auditor', models.CharField(max_length=100)),
                ('rut_cliente', models.CharField(max_length=12)),
                ('id_vivienda', models.CharField(max_length=50)),
                ('direccion_cliente', models.TextField()),
                ('marca', models.CharField(choices=[('claro', 'CLARO'), ('vtr', 'VTR')], max_length=10)),
                ('tecnologia', models.CharField(choices=[('hfc', 'HFC'), ('nftt', 'NFTT'), ('ftth', 'FTTH')], max_length=10)),
                ('estado_cliente', models.CharField(choices=[('autoriza', 'Autoriza a ingresar'), ('sin_moradores', 'Sin Moradores'), ('rechaza', 'Rechaza'), ('contingencia', 'Contingencia externa'), ('masivo', 'Incidencia Masivo ClaroVTR'), ('reagendo', 'Reagendó')], max_length=20)),
                ('fecha_reagendamiento', models.DateField(blank=True, null=True)),
                ('bloque_horario', models.CharField(blank=True, choices=[('10-13', '10:00 a 13:00'), ('14-18', '14:00 a 18:00')], max_length=20, null=True)),
                ('ont_instalada_correctamente', models.BooleanField(blank=True, null=True)),
                ('servicios_problema', models.JSONField(blank=True, default=list)),
                ('evaluacion_agendamiento', models.JSONField(blank=True, default=dict)),
                ('evaluacion_llegada', models.JSONField(blank=True, default=dict)),
                ('evaluacion_instalacion', models.JSONField(blank=True, default=dict)),
                ('evaluacion_configuracion', models.JSONField(blank=True, default=dict)),
                ('evaluacion_cierre', models.JSONField(blank=True, default=dict)),
                ('puntuacion_proceso', models.IntegerField(blank=True, null=True)),
                ('puntuacion_tecnico', models.IntegerField(blank=True, null=True)),
                ('puntuacion_recomendacion', models.IntegerField(blank=True, null=True)),
                ('solucion_gestion', models.CharField(blank=True, max_length=50)),
                ('tipo_orden_gestionada', models.CharField(blank=True, max_length=50)),
                ('tipo_problema', models.CharField(blank=True, max_length=50)),
                ('detalle_mala_practica', models.TextField(blank=True)),
                ('comentarios_agendamiento', models.TextField(blank=True)),
                ('comentarios_llegada', models.TextField(blank=True)),
                ('comentarios_instalacion', models.TextField(blank=True)),
                ('comentarios_configuracion', models.TextField(blank=True)),
                ('comentarios_cierre', models.TextField(blank=True)),
                ('descripcion_problema', models.TextField(blank=True)),
                ('foto_1_ruta', models.CharField(blank=True, max_length=255)),
                ('foto_2_ruta', models.CharField(blank=True, max_length=255)),
                ('foto_3_ruta', models.CharField(blank=True, max_length=255)),
                ('tecnico', models.ForeignKey(limit_choices_to={'rol': 'tecnico'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Instalación',
                'verbose_name_plural': 'Auditorías de Instalación',
            },
        ),
    ]
