# Generated by Django 5.2.6 on 2025-09-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_auditor', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=10)),
                ('tecnologia', models.CharField(max_length=10)),
                ('rut_cliente', models.CharField(max_length=20)),
                ('id_vivienda', models.CharField(max_length=50)),
                ('direccion_cliente', models.CharField(max_length=255)),
                ('estado_cliente', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='asignaciones.direccionasignada')),
            ],
            options={
                'verbose_name': 'Auditoría de Instalación',
                'verbose_name_plural': 'Auditorías de Instalación',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(blank=True, max_length=10)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='auditoria.auditoriavisita')),
            ],
        ),
        migrations.DeleteModel(
            name='AuditoriaInstalacion',
        ),
        migrations.AddIndex(
            model_name='auditoriavisita',
            index=models.Index(fields=['marca', 'tecnologia', 'estado_cliente'], name='auditoria_a_marca_1c7a56_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriavisita',
            index=models.Index(fields=['created_at'], name='auditoria_a_created_bb8ea3_idx'),
        ),
    ]
