# Generated by Django 5.2.6 on 2025-09-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_auditoriavisita_issue_delete_auditoriainstalacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriavisita',
            name='foto_1',
            field=models.ImageField(blank=True, null=True, upload_to='auditorias/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='auditorias/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='foto_3',
            field=models.ImageField(blank=True, null=True, upload_to='auditorias/%Y/%m/%d/'),
        ),
    ]
