# Generated by Django 5.2.6 on 2025-10-07 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0004_alter_historialasignacion_accion'),
        ('auditoria', '0003_remove_evidenciaservicio_auditoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='auditoria',
        ),
        migrations.AlterModelOptions(
            name='auditoriavisita',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='auditoriavisita',
            name='auditoria_a_marca_1c7a56_idx',
        ),
        migrations.RemoveField(
            model_name='auditoriavisita',
            name='direccion_cliente',
        ),
        migrations.RemoveField(
            model_name='auditoriavisita',
            name='foto_1',
        ),
        migrations.RemoveField(
            model_name='auditoriavisita',
            name='foto_2',
        ),
        migrations.RemoveField(
            model_name='auditoriavisita',
            name='foto_3',
        ),
        migrations.RemoveField(
            model_name='auditoriavisita',
            name='id_vivienda',
        ),
        migrations.RemoveField(
            model_name='auditoriavisita',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='auditoriavisita',
            name='nombre_auditor',
        ),
        migrations.RemoveField(
            model_name='auditoriavisita',
            name='rut_cliente',
        ),
        migrations.RemoveField(
            model_name='auditoriavisita',
            name='tecnologia',
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='bloque_agendamiento',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='bloque_cierre',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='bloque_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='bloque_llegada',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='bloque_proceso',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='categorias',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='descripcion_problema',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='fotos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='ont_modem_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='percepcion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='reagendado_bloque',
            field=models.CharField(blank=True, choices=[('10-13', '10:00-13:00'), ('14-18', '14:00-18:00')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='reagendado_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='servicios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditoriavisita',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='estado_cliente',
            field=models.CharField(choices=[('autoriza', 'Autoriza a ingresar'), ('sin_moradores', 'Sin Moradores'), ('rechaza', 'Rechaza'), ('contingencia', 'Contingencia externa'), ('masivo', 'Incidencia Masivo ClaroVTR'), ('reagendo', 'Reagendó')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditoriavisita',
            index=models.Index(fields=['estado_cliente'], name='auditoria_estado_idx'),
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
