# Generated by Django 5.2.6 on 2025-10-11 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0005_remove_direccionasignada_uniq_activa_por_cliente_vivienda_and_more'),
        ('auditoria', '0004_reshape_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditoriavisita',
            index=models.Index(fields=['asignacion', '-created_at'], name='auditoria_asig_created_idx'),
        ),
    ]
