# Generated by Django 5.2.6 on 2025-10-21 22:05

import auditoria.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0005_remove_direccionasignada_uniq_activa_por_cliente_vivienda_and_more'),
        ('auditoria', '0007_add_auditoria_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditoriavisita',
            name='auditoria_a_created_bb8ea3_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditoriavisita',
            name='auditoria_estado_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditoriavisita',
            name='auditoria_asig_created_idx',
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='arrival_comments',
            field=models.TextField(blank=True, db_column='q18_llegada_comentarios'),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='arrival_within_slot',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='llego_en_horario', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='asignaciones.direccionasignada'),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='asked_equipment_location',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='consulto_ubicacion', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='closure_comments',
            field=models.TextField(blank=True, db_column='q24_cierre_comentarios'),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='config_comments',
            field=models.TextField(blank=True, db_column='q22_config_comentarios'),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='configured_router',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='config_router', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='customer_status',
            field=models.CharField(blank=True, choices=[('AUTORIZA', 'Autoriza a ingresar'), ('SIN_MORADORES', 'Sin Moradores'), ('RECHAZA', 'Rechaza'), ('CONTINGENCIA', 'Contingencia externa'), ('MASIVO', 'Incidencia Masivo ClaroVTR'), ('REAGENDA', 'Reagendó')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='explained_before_start',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='explico_antes', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='final_problem_description',
            field=models.TextField(blank=True, db_column='q12_descripcion_problema'),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='got_consent_signature',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='pidio_conformidad', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='hfc_problem_description',
            field=models.TextField(blank=True, db_column='q73_desc_hfc'),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='identification_shown',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='se_identifico', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='info_type',
            field=models.CharField(blank=True, choices=[('mala_practica', 'Mala Práctica'), ('problema_general', 'Problema General')], db_column='info_tipo', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='install_process_comments',
            field=models.TextField(blank=True, db_column='q20_proceso_comentarios'),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='internet_issue_category',
            field=models.CharField(blank=True, choices=[('lento', 'Navegaba muy lento'), ('wifi_alcance', 'Señal del Wifi con bajo alcance'), ('cortes', 'Cortes/Días sin servicio'), ('intermitencia', 'Intermitencia de la Señal de Internet'), ('otro', 'Otro')], db_column='q9_internet_categoria', max_length=32),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='internet_issue_other',
            field=models.CharField(blank=True, db_column='q9_internet_otro', max_length=200),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='left_contact_info',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='dejo_contacto', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='left_instructions',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='dejo_instrucciones', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='malpractice_company_detail',
            field=models.CharField(blank=True, db_column='detalle_mala_practica_empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='malpractice_installer_detail',
            field=models.CharField(blank=True, db_column='detalle_mala_practica_instalador', max_length=200),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='nps_brand',
            field=models.PositiveSmallIntegerField(blank=True, db_column='nps_claro_vtr', null=True),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='nps_process',
            field=models.PositiveSmallIntegerField(blank=True, db_column='nps_proceso', null=True),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='nps_technician',
            field=models.PositiveSmallIntegerField(blank=True, db_column='nps_tecnico', null=True),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='ont_modem_ok',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='order_type',
            field=models.CharField(blank=True, choices=[('tecnica', 'Técnica'), ('comercial', 'Comercial')], db_column='orden_tipo', max_length=16),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='other_issue_description',
            field=models.TextField(blank=True, db_column='q11_otro_descripcion'),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='perception_notes',
            field=models.TextField(blank=True, db_column='q25_percepcion'),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='photo1',
            field=models.ImageField(blank=True, db_column='foto1', null=True, upload_to=auditoria.models._upload_auditoria),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='photo2',
            field=models.ImageField(blank=True, db_column='foto2', null=True, upload_to=auditoria.models._upload_auditoria),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='photo3',
            field=models.ImageField(blank=True, db_column='foto3', null=True, upload_to=auditoria.models._upload_auditoria),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='reschedule_date',
            field=models.DateField(blank=True, db_column='reagendado_fecha', null=True),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='reschedule_slot',
            field=models.CharField(blank=True, db_column='reagendado_bloque', help_text='Usar 10-13 o 14-18', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='resolution',
            field=models.CharField(blank=True, choices=[('terreno', 'Se solucionó en terreno'), ('orden', 'Se realizó una gestión con Orden')], db_column='solucion_gestion', max_length=16),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='reviewed_with_client',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='revision_con_cliente', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='schedule_comments',
            field=models.TextField(blank=True, db_column='q71_agend_comentarios'),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='schedule_informed_adult_required',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='agend_aviso_adulto', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='schedule_informed_datetime',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='agend_inf_fecha_hora', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='schedule_informed_services',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='agend_comunicacion_servicios', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='service_issues',
            field=models.JSONField(blank=True, db_column='servicios', default=list),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='tested_device',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='probo_dispositivo', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='tidy_and_safe_install',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='ordenado_seguro', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='tidy_cabling',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='cableado_prolijo', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='tv_functioning',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='tv_ok', default=3),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='tv_issue_category',
            field=models.CharField(blank=True, choices=[('sin_senal', 'Me quedaba sin señal de TV'), ('pixelado', 'Se pixelaba la imagen de TV'), ('intermitencia', 'Intermitencia de la Señal'), ('desfase', 'Presenta desfase con la señal en vivo'), ('streaming', 'Problemas con Plataforma de Streaming'), ('zapping', 'Problemas con zapping (lentitud)'), ('equipos', 'Problemas con Equipos (Dbox, Control, IPTV)'), ('otro', 'Otro')], db_column='q10_tv_categoria', max_length=32),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='tv_issue_other',
            field=models.CharField(blank=True, db_column='q10_tv_otro', max_length=200),
        ),
        migrations.AlterField(
            model_name='auditoriavisita',
            name='verified_signal_levels',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'No Aplica')], db_column='verifico_niveles', default=3),
        ),
    ]
