# Generated by Django 5.2.6 on 2025-10-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0008_fix_customer_status_colname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriavisita',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Auditoría de visita', 'verbose_name_plural': 'Auditorías de visitas'},
        ),
    ]
