# Generated by Django 5.2.6 on 2025-11-03 04:21

from django.db import migrations
from django.db.migrations.operations.special import SeparateDatabaseAndState

class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0011_sync_state_no_db'),
    ]

    operations = [
        # ==== Renombres (estos sí tocan BD) ====
        migrations.RenameField(
            model_name='auditoriavisita',
            old_name='malpractice_company_detail',
            new_name='detalle_mala_practica_empresa',
        ),
        migrations.RenameField(
            model_name='auditoriavisita',
            old_name='malpractice_installer_detail',
            new_name='detalle_mala_practica_instalador',
        ),
        migrations.RenameField(
            model_name='auditoriavisita',
            old_name='info_type',
            new_name='info_tipo',
        ),
        migrations.RenameField(
            model_name='auditoriavisita',
            old_name='nps_brand',
            new_name='nps_claro_vtr',
        ),
        migrations.RenameField(
            model_name='auditoriavisita',
            old_name='nps_process',
            new_name='nps_proceso',
        ),
        migrations.RenameField(
            model_name='auditoriavisita',
            old_name='nps_technician',
            new_name='nps_tecnico',
        ),
        migrations.RenameField(
            model_name='auditoriavisita',
            old_name='order_type',
            new_name='orden_tipo',
        ),
        migrations.RenameField(
            model_name='auditoriavisita',
            old_name='resolution',
            new_name='solucion_gestion',
        ),

        # ==== Remociones SOLO en el estado de Django (NO tocar BD) ====
        SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField('auditoriavisita', 'arrival_comments'),
                migrations.RemoveField('auditoriavisita', 'closure_comments'),
                migrations.RemoveField('auditoriavisita', 'config_comments'),
                migrations.RemoveField('auditoriavisita', 'final_problem_description'),
                migrations.RemoveField('auditoriavisita', 'hfc_problem_description'),
                migrations.RemoveField('auditoriavisita', 'install_process_comments'),
                migrations.RemoveField('auditoriavisita', 'internet_issue_category'),
                migrations.RemoveField('auditoriavisita', 'internet_issue_other'),
                migrations.RemoveField('auditoriavisita', 'other_issue_description'),
                migrations.RemoveField('auditoriavisita', 'perception_notes'),
                migrations.RemoveField('auditoriavisita', 'schedule_comments'),
                migrations.RemoveField('auditoriavisita', 'tv_issue_category'),
                migrations.RemoveField('auditoriavisita', 'tv_issue_other'),
            ],
            database_operations=[],
        ),
    ]
