# Generated by Django 5.2.6 on 2025-09-05 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tecnologia', models.CharField(choices=[('HFC', 'HFC'), ('NFTT', 'NFTT'), ('FTTH', 'FTTH')], max_length=10)),
                ('marca', models.CharField(choices=[('CLARO', 'CLARO'), ('VTR', 'VTR')], max_length=10)),
                ('rut_cliente', models.CharField(max_length=20)),
                ('id_vivienda', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('encuesta', models.CharField(choices=[('post_visita', 'post visita'), ('instalacion', 'instalación'), ('operaciones', 'operaciones')], max_length=20)),
                ('id_qualtrics', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('VISITADA', 'Visitada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, limit_choices_to={'rol': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['rut_cliente', 'id_vivienda'], name='asignacione_rut_cli_6f314c_idx'), models.Index(fields=['marca', 'tecnologia'], name='asignacione_marca_a5523d_idx'), models.Index(fields=['encuesta'], name='asignacione_encuest_540581_idx')],
            },
        ),
    ]
