# Generated by Django 5.2.6 on 2025-09-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tecnologia', models.CharField(choices=[('HFC', 'HFC'), ('NFTT', 'NFTT'), ('FTTH', 'FTTH')], max_length=10)),
                ('marca', models.CharField(choices=[('CLARO', 'CLARO'), ('VTR', 'VTR')], max_length=10)),
                ('rut_cliente', models.CharField(max_length=20)),
                ('id_vivienda', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(blank=True, max_length=80)),
                ('zona', models.CharField(blank=True, choices=[('NORTE', 'Norte'), ('CENTRO', 'Centro'), ('SUR', 'Sur')], max_length=10)),
                ('encuesta', models.CharField(choices=[('post_visita', 'post visita'), ('instalacion', 'instalación'), ('operaciones', 'operaciones')], max_length=20)),
                ('id_qualtrics', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('VISITADA', 'Visitada'), ('CANCELADA', 'Cancelada'), ('REAGENDADA', 'Reagendada')], default='PENDIENTE', max_length=10)),
                ('reagendado_fecha', models.DateField(blank=True, null=True)),
                ('reagendado_bloque', models.CharField(blank=True, choices=[('10-13', '10:00 a 13:00'), ('14-18', '14:00 a 18:00')], max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asignaciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADA', 'Creada'), ('ASIGNADA_TECNICO', 'Asignada a técnico'), ('ESTADO_CLIENTE', 'Estado del cliente'), ('REAGENDADA', 'Reagendada'), ('CERRADA', 'Cerrada'), ('AUDITORIA_CREADA', 'Auditoría creada')], max_length=32)),
                ('detalles', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historial_asignaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reagendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anterior', models.DateField(blank=True, null=True)),
                ('bloque_anterior', models.CharField(blank=True, choices=[('10-13', '10:00 a 13:00'), ('14-18', '14:00 a 18:00')], max_length=5, null=True)),
                ('fecha_nueva', models.DateField()),
                ('bloque_nuevo', models.CharField(choices=[('10-13', '10:00 a 13:00'), ('14-18', '14:00 a 18:00')], max_length=5)),
                ('motivo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reagendamientos',
            },
        ),
    ]
