# Generated by Django 5.2.6 on 2025-09-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tecnologia', models.CharField(choices=[('HFC', 'HFC'), ('NFTT', 'NFTT'), ('FTTH', 'FTTH')], help_text='Tecnología del servicio (FTTH/HFC/NFTT).', max_length=10)),
                ('marca', models.CharField(choices=[('CLARO', 'CLARO'), ('VTR', 'VTR')], max_length=10)),
                ('rut_cliente', models.CharField(max_length=20)),
                ('id_vivienda', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('encuesta', models.CharField(choices=[('post_visita', 'post visita'), ('instalacion', 'instalación'), ('operaciones', 'operaciones')], max_length=20)),
                ('id_qualtrics', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('VISITADA', 'Visitada'), ('CANCELADA', 'Cancelada'), ('REAGENDADA', 'Reagendada')], default='PENDIENTE', max_length=10)),
                ('reagendado_fecha', models.DateField(blank=True, null=True)),
                ('reagendado_bloque', models.CharField(blank=True, choices=[('10-13', '10:00 a 13:00'), ('14-18', '14:00 a 18:00')], max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
