# Generated by Django 5.2.6 on 2025-09-12 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionasignada',
            name='asignado_a',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialasignacion',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='asignaciones.direccionasignada'),
        ),
        migrations.AddField(
            model_name='historialasignacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reagendamiento',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagendamientos', to='asignaciones.direccionasignada'),
        ),
        migrations.AddField(
            model_name='reagendamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='direccionasignada',
            index=models.Index(fields=['rut_cliente', 'id_vivienda'], name='asignacione_rut_cli_fa0b02_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionasignada',
            index=models.Index(fields=['marca', 'tecnologia'], name='asignacione_marca_f5bbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionasignada',
            index=models.Index(fields=['encuesta'], name='asignacione_encuest_553623_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionasignada',
            index=models.Index(fields=['comuna'], name='asignacione_comuna_3d37ad_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionasignada',
            index=models.Index(fields=['zona'], name='asignacione_zona_146298_idx'),
        ),
        migrations.AddConstraint(
            model_name='direccionasignada',
            constraint=models.UniqueConstraint(condition=models.Q(('asignado_a__isnull', False), ('estado__in', ['PENDIENTE', 'ASIGNADA', 'REAGENDADA'])), fields=('rut_cliente', 'id_vivienda'), name='uniq_activa_por_cliente_vivienda'),
        ),
    ]
