# Generated by Django 5.2.6 on 2025-09-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionasignada',
            name='reagendado_bloque',
            field=models.CharField(blank=True, choices=[('10-13', '10:00 a 13:00'), ('14-18', '14:00 a 18:00')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='direccionasignada',
            name='reagendado_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('VISITADA', 'Visitada'), ('CANCELADA', 'Cancelada'), ('REAGENDADA', 'Reagendada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=10),
        ),
    ]
