# Generated by Django 5.2.6 on 2025-09-12 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionasignada',
            name='asignado_a',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='direccionasignada',
            index=models.Index(fields=['rut_cliente', 'id_vivienda'], name='asignacione_rut_cli_6f314c_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionasignada',
            index=models.Index(fields=['marca', 'tecnologia'], name='asignacione_marca_a5523d_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionasignada',
            index=models.Index(fields=['encuesta'], name='asignacione_encuest_540581_idx'),
        ),
    ]
