# Generated by Django 5.2.6 on 2025-09-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_direccionasignada_reagendado_bloque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionasignada',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('VISITADA', 'Visitada'), ('CANCELADA', 'Cancelada'), ('REAGENDADA', 'Reagendada')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='tecnologia',
            field=models.CharField(choices=[('HFC', 'HFC'), ('NFTT', 'NFTT'), ('FTTH', 'FTTH')], help_text='Tecnología del servicio (FTTH/HFC/NFTT).', max_length=10),
        ),
    ]
