# Generated by Django 5.2.6 on 2025-09-22 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccionasignada',
            options={'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='historialasignacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historial de dirección', 'verbose_name_plural': 'Historial de direcciones'},
        ),
        migrations.AlterModelOptions(
            name='reagendamiento',
            options={'verbose_name': 'Reagendamiento', 'verbose_name_plural': 'Reagendamientos'},
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='asignado_a',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='comuna',
            field=models.CharField(blank=True, max_length=80, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección del cliente'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='encuesta',
            field=models.CharField(choices=[('post_visita', 'post visita'), ('instalacion', 'instalación'), ('operaciones', 'operaciones')], max_length=20, verbose_name='Encuesta de origen'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('VISITADA', 'Visitada'), ('CANCELADA', 'Cancelada'), ('REAGENDADA', 'Reagendada')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='id_qualtrics',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID Qualtrics'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='id_vivienda',
            field=models.CharField(max_length=50, verbose_name='ID vivienda'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='marca',
            field=models.CharField(choices=[('CLARO', 'CLARO'), ('VTR', 'VTR')], max_length=10, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='reagendado_bloque',
            field=models.CharField(blank=True, choices=[('10-13', '10:00 a 13:00'), ('14-18', '14:00 a 18:00')], help_text='Solo se completa cuando el cliente reagenda.', max_length=5, null=True, verbose_name='Reagendado bloque'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='reagendado_fecha',
            field=models.DateField(blank=True, help_text='Solo se completa cuando el cliente reagenda.', null=True, verbose_name='Reagendado fecha'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='rut_cliente',
            field=models.CharField(max_length=20, verbose_name='RUT cliente'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='tecnologia',
            field=models.CharField(choices=[('HFC', 'HFC'), ('NFTT', 'NFTT'), ('FTTH', 'FTTH')], max_length=10, verbose_name='Tecnología'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='zona',
            field=models.CharField(blank=True, choices=[('NORTE', 'Norte'), ('CENTRO', 'Centro'), ('SUR', 'Sur')], max_length=10, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='historialasignacion',
            name='accion',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ASIGNADA_TECNICO', 'Asignada a técnico'), ('ESTADO_CLIENTE', 'Estado del cliente'), ('REAGENDADA', 'Reagendada'), ('CERRADA', 'Cerrada'), ('AUDITORIA_CREADA', 'Auditoría creada'), ('EDITADA', 'Editada')], max_length=32, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='historialasignacion',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='asignaciones.direccionasignada', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historialasignacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='historialasignacion',
            name='detalles',
            field=models.TextField(blank=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='historialasignacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='reagendamiento',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagendamientos', to='asignaciones.direccionasignada', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='reagendamiento',
            name='bloque_anterior',
            field=models.CharField(blank=True, choices=[('10-13', '10:00 a 13:00'), ('14-18', '14:00 a 18:00')], max_length=5, null=True, verbose_name='Bloque anterior'),
        ),
        migrations.AlterField(
            model_name='reagendamiento',
            name='bloque_nuevo',
            field=models.CharField(choices=[('10-13', '10:00 a 13:00'), ('14-18', '14:00 a 18:00')], max_length=5, verbose_name='Bloque nuevo'),
        ),
        migrations.AlterField(
            model_name='reagendamiento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='reagendamiento',
            name='fecha_anterior',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha anterior'),
        ),
        migrations.AlterField(
            model_name='reagendamiento',
            name='fecha_nueva',
            field=models.DateField(verbose_name='Fecha nueva'),
        ),
        migrations.AlterField(
            model_name='reagendamiento',
            name='motivo',
            field=models.TextField(verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='reagendamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
