# Generated by Django 5.2.6 on 2025-10-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_alter_direccionasignada_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialasignacion',
            name='accion',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ASIGNADA_TECNICO', 'Asignada a técnico'), ('ESTADO_CLIENTE', 'Estado del cliente'), ('REAGENDADA', 'Reagendada'), ('CERRADA', 'Cerrada'), ('AUDITORIA_CREADA', 'Auditoría creada')], max_length=32, verbose_name='Acción'),
        ),
    ]
