# Generated by Django 5.2.6 on 2025-10-11 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0004_alter_historialasignacion_accion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='direccionasignada',
            name='uniq_activa_por_cliente_vivienda',
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='id_vivienda',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID vivienda'),
        ),
        migrations.AddIndex(
            model_name='direccionasignada',
            index=models.Index(fields=['estado'], name='asignacione_estado_4add16_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionasignada',
            index=models.Index(fields=['fecha'], name='asignacione_fecha_89be0e_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionasignada',
            index=models.Index(fields=['asignado_a'], name='asignacione_asignad_0af72d_idx'),
        ),
        migrations.AddConstraint(
            model_name='direccionasignada',
            constraint=models.UniqueConstraint(condition=models.Q(('id_vivienda__isnull', False), models.Q(('id_vivienda', ''), _negated=True)), fields=('id_vivienda',), name='uniq_id_vivienda_when_present'),
        ),
    ]
