# Generated by Django 5.2.6 on 2025-10-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0006_centro_a_oriente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionasignada',
            name='zona',
            field=models.CharField(blank=True, choices=[('NORTE', 'Norte'), ('ORIENTE', 'Oriente'), ('SUR', 'Sur')], max_length=10, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='historialasignacion',
            name='accion',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ASIGNADA_TECNICO', 'Asignada a técnico'), ('ESTADO_CLIENTE', 'Estado del cliente'), ('REAGENDADA', 'Reagendada'), ('CERRADA', 'Cerrada'), ('AUDITORIA_CREADA', 'Auditoría creada'), ('EDITADA', 'Editada'), ('DESASIGNADA', 'Desasignada')], max_length=32, verbose_name='Acción'),
        ),
    ]
