# Generated by Django 5.2.6 on 2025-10-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0007_alter_direccionasignada_zona_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccionasignada',
            options={'verbose_name': 'Dirección asignada', 'verbose_name_plural': 'Direcciones asignadas'},
        ),
        migrations.AlterModelOptions(
            name='historialasignacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historial de asignación', 'verbose_name_plural': 'Historial de asignaciones'},
        ),
        migrations.AlterField(
            model_name='direccionasignada',
            name='zona',
            field=models.CharField(blank=True, max_length=40, verbose_name='Zona'),
        ),
    ]
