# Generated by Django 5.2.6 on 2025-10-11 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0005_remove_direccionasignada_uniq_activa_por_cliente_vivienda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REAGENDO', 'Reagendo')], max_length=20)),
                ('destinatario', models.EmailField(blank=True, max_length=254, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('estado', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='asignaciones.direccionasignada')),
            ],
        ),
    ]
