# Generated by Django 5.2.6 on 2025-10-12 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0005_remove_direccionasignada_uniq_activa_por_cliente_vivienda_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='estado',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='asunto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='canal',
            field=models.CharField(choices=[('none', 'Sin envío'), ('email', 'Email'), ('webhook', 'Webhook'), ('sms', 'SMS')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destino',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('queued', 'En cola'), ('sent', 'Enviado'), ('failed', 'Falló')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='asignaciones.direccionasignada'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificaciones',
        ),
    ]
