# Generated by Django 5.2.6 on 2025-10-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notificacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('valor', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('str', 'Str'), ('int', 'Int'), ('bool', 'Bool'), ('json', 'JSON')], default='str', max_length=16)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
                'db_table': 'configuracion',
            },
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ('-created_at',), 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CONFIG_CREATE', 'Config: crear'), ('CONFIG_UPDATE', 'Config: actualizar'), ('CONFIG_DELETE', 'Config: eliminar'), ('USER_CREATE', 'Usuario: crear'), ('USER_UPDATE', 'Usuario: actualizar'), ('USER_DEACTIVATE', 'Usuario: desactivar'), ('USER_REACTIVATE', 'Usuario: reactivar'), ('USER_ROLE_UPDATE', 'Usuario: cambiar rol'), ('USER_DELETE', 'Usuario: eliminar')], max_length=32)),
                ('detalle', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs_sistema',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
