# Generated by Django 5.2.6 on 2025-11-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracion_alter_notificacion_options_logsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='canal',
            field=models.CharField(choices=[('none', 'Sin envío'), ('email', 'Email'), ('webhook', 'Webhook'), ('sms', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='email', max_length=20),
        ),
    ]
