# Generated by Django 5.2.6 on 2025-09-03 22:25

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut_usuario', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('rol', models.CharField(choices=[('tecnico', 'Técnico'), ('auditor', 'Auditor'), ('admin', 'Administrador')], default='tecnico', max_length=10, verbose_name='Rol')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre usuario')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=50, verbose_name='Zona')),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'db_table': 'tecnicos',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('cliente_apellido', models.CharField(max_length=100, verbose_name='Apellido Cliente')),
                ('cliente_direccion', models.TextField(verbose_name='Dirección')),
                ('cliente_comuna', models.CharField(max_length=50, verbose_name='Comuna')),
                ('cliente_telefono', models.CharField(max_length=20, verbose_name='Teléfono Cliente')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('hora_programada', models.TimeField(verbose_name='Hora Programada')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('reagendada', 'Reagendada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('tipo_servicio', models.CharField(choices=[('instalacion', 'Instalación'), ('mantenimiento', 'Mantenimiento'), ('reparacion', 'Reparación'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Servicio')),
                ('descripcion_servicio', models.TextField(blank=True, null=True, verbose_name='Descripción del Servicio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('tecnico', models.ForeignKey(db_column='tecnico_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.tecnico', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'visitas',
            },
        ),
        migrations.CreateModel(
            name='Reagendamiento',
            fields=[
                ('id_reagendamiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_anterior', models.DateField(verbose_name='Fecha Anterior')),
                ('hora_anterior', models.TimeField(verbose_name='Hora Anterior')),
                ('fecha_nueva', models.DateField(verbose_name='Fecha Nueva')),
                ('hora_nueva', models.TimeField(verbose_name='Hora Nueva')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('visita', models.ForeignKey(db_column='visita_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.visita', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Reagendamiento',
                'verbose_name_plural': 'Reagendamientos',
                'db_table': 'reagendamientos',
            },
        ),
        migrations.CreateModel(
            name='HistorialVisita',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('creada', 'Creada'), ('reagendada', 'Reagendada'), ('completada', 'Completada'), ('nota_agregada', 'Nota Agregada'), ('cancelada', 'Cancelada'), ('estado_cambiado', 'Estado Cambiado')], max_length=20, verbose_name='Acción')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('visita', models.ForeignKey(db_column='visita_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.visita', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Historial de Visita',
                'verbose_name_plural': 'Historial de Visitas',
                'db_table': 'historial_visitas',
            },
        ),
        migrations.CreateModel(
            name='EvidenciaServicio',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evidencia', models.CharField(choices=[('foto', 'Foto'), ('firma', 'Firma'), ('comprobante', 'Comprobante'), ('otro', 'Otro')], default='foto', max_length=20, verbose_name='Tipo de Evidencia')),
                ('archivo_ruta', models.CharField(max_length=255, verbose_name='Ruta de Archivo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('visita', models.ForeignKey(db_column='visita_id', on_delete=django.db.models.deletion.CASCADE, to='usuarios.visita', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Evidencia de Servicio',
                'verbose_name_plural': 'Evidencias de Servicio',
                'db_table': 'evidencias_servicio',
            },
        ),
    ]
