services:
  backend:
    build: ./backend
    container_name: proyecto-backend
    command: gunicorn claro_project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build: ./frontend
    container_name: proyecto-frontend
    env_file:
      - ./.env
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
